# 定时重新部署，国际时间0点，即早上8点。
on:
  push:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    ### 自定部署
    - name: Deploy to LeanEngine
      uses: enflo/curl-action@master
      with:
        curl: -X POST https://leancloud.cn/1.1/engine/groups/web/production/version?gitTag=master&token=${{ secrets.DEPLOY_TOKEN }}
